[package]
name = "rezasm-app"
version = "0.4.0"
edition = "2021"

[dependencies]
rezasm-core = { path = "rezasm-core" }
rezasm-macro = { path = "rezasm-macro" }

lazy_static = "1.4.0"
regex = "1.8.1"
bimap = "0.6.3"
bytebuffer = "2.1.0"
clap = { version = "4.4.1", features = ["derive"] }
expanduser = "1.2.2"
