[package]
name = "rezasm"
version = "0.2.0"
edition = "2021"

[[bin]]
path = "rezasm-app/src/main.rs"
name = "rezasm-app"

[[bin]]
path = "rezasm-web/main.rs"
name = "rezasm"

# For rezasm-web only
[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
rezasm-core = { path = "rezasm-app/rezasm-core" }
rezasm-macro = { path = "rezasm-app/rezasm-macro" }
rezasm-app = { path = "rezasm-app" }

bimap = "0.6.3"
bytebuffer = "2.1.1"
clap = { version = "4.4.1", features = ["derive"] }
expanduser = "1.2.2"
lazy_static = "1.4.0"
regex = "1.8.4"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"

# For rezasm-web only
tauri = { version = "1.4.1", features = ["shell-open"] }
tokio = { version = "1.32.0", features = ["full"] }
thiserror = "1.0.48"

[workspace]
members = ["rezasm-app", "rezasm-app/rezasm-core", "rezasm-app/rezasm-macro"]

# For rezasm-web only
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
[features]
custom-protocol = ["tauri/custom-protocol"]
