// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!|QVQPOOObQPO'#CaO{QPO'#CcO!YQPO'#C`O!eQPO'#C_OOQO'#Cn'#CnQVQPOOOOQO,58{,58{OOQO'#Ce'#CeOOQO'#Co'#CoO!mQPO,58}OOQO,58z,58zOOQO,58y,58yOOQO-E6l-E6lOOQO-E6m-E6m",
  stateData: "#V~OPOS~OUPOWQO_RO~OfVO~OUXOYWOZWO[WO]XO^XO~O_VX`VXaVX~PgO_ZO`SXaSX~O`[Oa[O~O_Va`VaaVa~PgO`PY[Z^]WUZ~",
  goto: "!RdPPPeimPmPqPPPPPPPPu{TTOUTSOUTROUTXQYQUOR]UQYQR^Y",
  nodeNames: "⚠ Space Program Line Content LabelDefinition Label Instruction InstructionName Number Binary Decimal Hexadecimal Register Dereference Comment NewLine EOF",
  maxTerm: 22,
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "*z~ReXY!dYZ#XZ^!dpq!dst$Otu$gxy%R!Q!R%y!R!['R![!]*`!c!}'i#T#o*e#y#z!d$f$g!d#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~~*u~!iYP~X^!dpq!d#y#z!d$f$g!d#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~#`Y`~P~X^!dpq!d#y#z!d$f$g!d#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~$TS_~OY$OZ;'S$O;'S;=`$a<%lO$O~$dP;=`<%l$O~$jR!Q![$s!c!}$s#T#o$s~$xR]~!Q![$s!c!}$s#T#o$s~%UPtu%X~%[R!Q![%e!c!}%e#T#o%e~%hSyz%t!Q![%e!c!}%e#T#o%e~%yO^~~&Q]Z~U~xy%R!O!P&y!Q!['R!c!d'i!d!e'w!e!z'i!z!{)R!{!}'i#T#U'i#U#V'w#V#l'i#l#m)R#m#o'i~'OPZ~!Q![&y~'YTZ~U~xy%R!O!P&y!Q!['R!c!}'i#T#o'i~'nRU~!Q!['i!c!}'i#T#o'i~'|TU~!Q!R(]!R!S(]!S!['i!c!}'i#T#o'i~(dUY~U~!O!P(v!Q!R(]!R!S(]!S!['i!c!}'i#T#o'i~({QY~!Q!R(v!R!S(v~)WTU~!Q![)g!c!i)g!i!}'i#T#Z)g#Z#o'i~)nU[~U~!O!P*Q!Q![)g!c!i)g!i!}'i#T#Z)g#Z#o'i~*VR[~!Q![*Q!c!i*Q#T#Z*Q~*eOf~~*lRW~U~!Q!['i!c!}'i#T#o*e~*zOa~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 88
})
