// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Space = 1,
  Program = 2,
  Line = 3,
  Content = 4,
  LabelDefinition = 5,
  Label = 6,
  Instruction = 7,
  InstructionName = 8,
  Number = 9,
  Binary = 10,
  Decimal = 11,
  Hexadecimal = 12,
  Register = 13,
  Dereference = 14,
  Comment = 15,
  NewLine = 16,
  EOF = 17
