// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Space = 1,
  Comment = 2,
  Program = 3,
  Label = 4,
  Instruction = 5,
  InstructionName = 6,
  Terminal = 7,
  Character = 8,
  StringLiteral = 9,
  NumberLiteral = 10,
  Dereference = 11,
  Register = 12,
  LabelReference = 13

