// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!QOYQPOOOvQQO'#CaOOQO'#Cm'#CmQOQPOOOOQO'#Cc'#CcOOQO'#Cj'#CjO}QQO,58{OOQO-E6h-E6h",
  stateData: "!U~OPOSQOS~OSQOUPO~OWSOXSOYSOZSO[SO]SO~O_TX~PbO_Ta~PbO",
  goto: "sbPPPPPcPfPPPPPPjPPpRQOTTPUQUPRVURRO",
  nodeNames: "⚠ Space Comment Program Label Instruction InstructionName Terminal Character StringLiteral NumberLiteral Dereference Register LabelReference",
  maxTerm: 17,
  skippedNodes: [0,1,2],
  repeatNodeCount: 1,
  tokenData: "1Q~RdX^!apq!ars#Ust$Ytu$qwx%ixy&Z}!O't!Q!R*{!R![+}!c!}.}#T#o/o#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~!fYP~X^!apq!a#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~#XUOY#UZr#Urs#ks;'S#U;'S;=`$S<%lO#U~#pUX~OY#UZr#Urs#ks;'S#U;'S;=`$S<%lO#U~$VP;=`<%l#U~$_SQ~OY$YZ;'S$Y;'S;=`$k<%lO$Y~$nP;=`<%l$Y~$tSOt%Qu;'S%Q;'S;=`%c<%lO%Q~%VS[~Ot%Qu;'S%Q;'S;=`%c<%lO%Q~%fP;=`<%l%Q~%lSOY%xZ;'S%x;'S;=`&T<%lO%x~%{Pwx&O~&TOW~~&WP;=`<%l%x~&^Ptu&a~&dSOt&pu;'S&p;'S;=`'n<%lO&p~&sUOt&puy&pyz'Vz;'S&p;'S;=`'n<%lO&p~'[UZ~Ot&puy&pyz'Vz;'S&p;'S;=`'n<%lO&p~'qP;=`<%l&p~'wRxy&Z!Q!R(Q!R![({~(TWxy&Z!O!P(m!Q![({!d!e)[!z!{*O#U#V)[#l#m*O~~(vQ(pQ!Q![(m~~(vQ({OYQ~)OSxy&Z!O!P(m!Q![({~~(vQ)_Q!Q!R)e!R!S)eQ)jRYQ!O!P)s!Q!R)e!R!S)eQ)xQYQ!Q!R)s!R!S)sQ*RR!Q![*[!c!i*[#T#Z*[Q*aSYQ!O!P*m!Q![*[!c!i*[#T#Z*[Q*rRYQ!Q![*m!c!i*m#T#Z*m~+O_xy&Z!O!P(m!Q![+}![!],g!c!d,l!d!e,{!e!z,l!z!{-|!{!},l#T#U,l#U#V,{#V#l,l#l#m-|#m#o,l~~(v~,QVxy&Z!O!P(m!Q![+}![!],g!c!},l#T#o,l~~(vP,lOSPP,oS!Q![,l![!],g!c!},l#T#o,lR-OU!Q!R-b!R!S-b!S![,l![!],g!c!},l#T#o,lR-gVYQ!O!P)s!Q!R-b!R!S-b!S![,l![!],g!c!},l#T#o,lR.PU!Q![.c![!],g!c!i.c!i!},l#T#Z.c#Z#o,lR.hVYQ!O!P*m!Q![.c![!],g!c!i.c!i!},l#T#Z.c#Z#o,lR/QS!Q![/^![!],g!c!}/^#T#o/^R/cS]Q!Q![/^![!],g!c!}/^#T#o/^R/rYO!Q0b!Q![0g![!],g!]!c0b!c!}0g!}#T0b#T#o0g#o;'S0b;'S;=`0z<%lO0bP0gOUPR0nSUP]Q!Q![/^![!],g!c!}/^#T#o/^P0}P;=`<%l0b",
  tokenizers: [0, 1],
  topRules: {"Program":[0,3]},
  tokenPrec: 0
})
