[package]
name = "rezasm-macro"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
rezasm-core = { path = "../rezasm-core", version = "*" }

quote = "1.0.33"
proc-macro2 = "1.0.66"
syn = { version = "2.0.29", features = ["full", "extra-traits"] }
