[package]
name = "rezasm-core"
version = "1.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bimap = "0.6.3"
bytebuffer = "2.1.0"
lazy_static = "1.4.0"
regex = "1.8.1"
scanner-rust = "2.0.16"
thiserror = "1.0.47"
